// ============================================================
// LISTE DES CODES GAGNANTS — ChickNSter
// ============================================================
// Ce fichier est utilise a la fois par la page client (la roue)
// et par la page caisse. Modifiez UNIQUEMENT ce fichier pour
// ajouter ou retirer des codes -- inutile de toucher aux deux
// autres fichiers HTML.
//
// Chaque code est associe a un produit precis (le meme que celui
// affiche au client sur la roue). La page caisse affiche ce produit
// quand le code est valide.
//
// Regles :
//  - Chaque "code" doit faire exactement 4 chiffres (entre "0000" et "9999").
//  - Chaque code doit etre unique dans la liste (pas de doublon).
//  - "prize" doit etre exactement l'un de ces 4 noms (memes accents/majuscules
//    que sur la page client) : "Waffle Fries", "Boisson", "Sundae", "Cookie".
//  - Vous pouvez ajouter autant de codes que vous voulez, a tout moment.
//  - N'oubliez pas de re-publier / re-televerser ce fichier apres modification,
//    sur les DEUX pages (client et caisse), pour que le changement soit pris en compte.
// ============================================================

var VALID_CODES = [
  {code:"2169", prize:"Boisson"},
  {code:"2307", prize:"Boisson"},
  {code:"2674", prize:"Boisson"},
  {code:"3287", prize:"Boisson"},
  {code:"3547", prize:"Boisson"},
  {code:"3664", prize:"Boisson"},
  {code:"3677", prize:"Boisson"},
  {code:"4257", prize:"Boisson"},
  {code:"4593", prize:"Boisson"},
  {code:"4598", prize:"Boisson"},
  {code:"4657", prize:"Boisson"},
  {code:"4733", prize:"Boisson"},
  {code:"4811", prize:"Boisson"},
  {code:"5339", prize:"Boisson"},
  {code:"5557", prize:"Boisson"},
  {code:"6155", prize:"Boisson"},
  {code:"6514", prize:"Boisson"},
  {code:"6635", prize:"Boisson"},
  {code:"6977", prize:"Boisson"},
  {code:"7482", prize:"Boisson"},
  {code:"7543", prize:"Boisson"},
  {code:"8359", prize:"Boisson"},
  {code:"9085", prize:"Boisson"},
  {code:"9348", prize:"Boisson"},
  {code:"9785", prize:"Boisson"},
  {code:"1488", prize:"Cookie"},
  {code:"2084", prize:"Cookie"},
  {code:"2139", prize:"Cookie"},
  {code:"2489", prize:"Cookie"},
  {code:"2584", prize:"Cookie"},
  {code:"3266", prize:"Cookie"},
  {code:"4456", prize:"Cookie"},
  {code:"4582", prize:"Cookie"},
  {code:"5010", prize:"Cookie"},
  {code:"5012", prize:"Cookie"},
  {code:"5304", prize:"Cookie"},
  {code:"5386", prize:"Cookie"},
  {code:"5422", prize:"Cookie"},
  {code:"5554", prize:"Cookie"},
  {code:"5741", prize:"Cookie"},
  {code:"5803", prize:"Cookie"},
  {code:"6168", prize:"Cookie"},
  {code:"6820", prize:"Cookie"},
  {code:"7201", prize:"Cookie"},
  {code:"7224", prize:"Cookie"},
  {code:"7912", prize:"Cookie"},
  {code:"8517", prize:"Cookie"},
  {code:"9751", prize:"Cookie"},
  {code:"9830", prize:"Cookie"},
  {code:"9935", prize:"Cookie"},
  {code:"1106", prize:"Sundae"},
  {code:"1409", prize:"Sundae"},
  {code:"1434", prize:"Sundae"},
  {code:"1711", prize:"Sundae"},
  {code:"2291", prize:"Sundae"},
  {code:"2424", prize:"Sundae"},
  {code:"2535", prize:"Sundae"},
  {code:"2654", prize:"Sundae"},
  {code:"2679", prize:"Sundae"},
  {code:"3045", prize:"Sundae"},
  {code:"3803", prize:"Sundae"},
  {code:"4150", prize:"Sundae"},
  {code:"4432", prize:"Sundae"},
  {code:"4527", prize:"Sundae"},
  {code:"4611", prize:"Sundae"},
  {code:"4752", prize:"Sundae"},
  {code:"5040", prize:"Sundae"},
  {code:"5374", prize:"Sundae"},
  {code:"5506", prize:"Sundae"},
  {code:"6930", prize:"Sundae"},
  {code:"7065", prize:"Sundae"},
  {code:"7216", prize:"Sundae"},
  {code:"7572", prize:"Sundae"},
  {code:"8428", prize:"Sundae"},
  {code:"8527", prize:"Sundae"},
  {code:"1520", prize:"Waffle Fries"},
  {code:"1525", prize:"Waffle Fries"},
  {code:"1750", prize:"Waffle Fries"},
  {code:"1916", prize:"Waffle Fries"},
  {code:"2519", prize:"Waffle Fries"},
  {code:"2824", prize:"Waffle Fries"},
  {code:"3286", prize:"Waffle Fries"},
  {code:"3340", prize:"Waffle Fries"},
  {code:"3615", prize:"Waffle Fries"},
  {code:"4483", prize:"Waffle Fries"},
  {code:"4814", prize:"Waffle Fries"},
  {code:"5333", prize:"Waffle Fries"},
  {code:"5552", prize:"Waffle Fries"},
  {code:"6313", prize:"Waffle Fries"},
  {code:"6574", prize:"Waffle Fries"},
  {code:"6881", prize:"Waffle Fries"},
  {code:"6925", prize:"Waffle Fries"},
  {code:"7227", prize:"Waffle Fries"},
  {code:"7873", prize:"Waffle Fries"},
  {code:"7924", prize:"Waffle Fries"},
  {code:"8019", prize:"Waffle Fries"},
  {code:"8573", prize:"Waffle Fries"},
  {code:"9179", prize:"Waffle Fries"},
  {code:"9279", prize:"Waffle Fries"},
  {code:"9928", prize:"Waffle Fries"},
  // Ajoutez vos nouveaux codes ici, par exemple :
  // {code:"1234", prize:"Cookie"},
];
